import 'vuetify/styles'
import { createVuetify } from 'vuetify'
import { aliases as mdiAliases, mdi } from 'vuetify/iconsets/mdi-svg'
import {
  mdiAccount,
  mdiAccountGroup,
  mdiAlertCircle,
  mdiAlertCircleOutline,
  mdiArrowLeft,
  mdiAttachment,
  mdiBell,
  mdiBellPlusOutline,
  mdiBellRingOutline,
  mdiBullhornOutline,
  mdiCalendar,
  mdiCalendarBlankOutline,
  mdiCalendarCheck,
  mdiCalendarClock,
  mdiCalendarToday,
  mdiCheck,
  mdiCheckAll,
  mdiCheckCircleOutline,
  mdiChevronLeft,
  mdiChevronRight,
  mdiCircle,
  mdiClockAlert,
  mdiClockAlertOutline,
  mdiClockOutline,
  mdiClose,
  mdiComment,
  mdiContentCopy,
  mdiContentSaveOutline,
  mdiDelete,
  mdiEmailOutline,
  mdiDomain,
  mdiFileDocumentOutline,
  mdiFileDownload,
  mdiFilterVariant,
  mdiFlask,
  mdiFolder,
  mdiFolderCog,
  mdiFolderStarOutline,
  mdiHome,
  mdiInboxOutline,
  mdiLink,
  mdiMagnify,
  mdiMagnifyMinus,
  mdiMagnifyPlus,
  mdiMagnifyScan,
  mdiMapMarker,
  mdiPencil,
  mdiPin,
  mdiPinOutline,
  mdiPlus,
  mdiRefresh,
  mdiRobot,
  mdiSchool,
  mdiShareVariant,
  mdiStar,
  mdiStarOutline,
  mdiTagMultiple,
  mdiTagOffOutline,
  mdiTagPlus,
  mdiTextBox,
  mdiTrayArrowUp,
  mdiTrophy,
} from '@mdi/js'

export default createVuetify({
  icons: {
    defaultSet: 'mdi',
    aliases: {
      ...mdiAliases,
      account: mdiAccount,
      accountGroup: mdiAccountGroup,
      alertCircle: mdiAlertCircle,
      alertCircleOutline: mdiAlertCircleOutline,
      arrowLeft: mdiArrowLeft,
      attachment: mdiAttachment,
      bell: mdiBell,
      bellPlusOutline: mdiBellPlusOutline,
      bellRingOutline: mdiBellRingOutline,
      bullhornOutline: mdiBullhornOutline,
      calendar: mdiCalendar,
      calendarBlankOutline: mdiCalendarBlankOutline,
      calendarCheck: mdiCalendarCheck,
      calendarClock: mdiCalendarClock,
      calendarToday: mdiCalendarToday,
      check: mdiCheck,
      checkAll: mdiCheckAll,
      checkCircleOutline: mdiCheckCircleOutline,
      chevronLeft: mdiChevronLeft,
      chevronRight: mdiChevronRight,
      circle: mdiCircle,
      clockAlert: mdiClockAlert,
      clockAlertOutline: mdiClockAlertOutline,
      clockOutline: mdiClockOutline,
      close: mdiClose,
      comment: mdiComment,
      contentCopy: mdiContentCopy,
      contentSaveOutline: mdiContentSaveOutline,
      delete: mdiDelete,
      emailOutline: mdiEmailOutline,
      domain: mdiDomain,
      fileDocumentOutline: mdiFileDocumentOutline,
      fileDownload: mdiFileDownload,
      filterVariant: mdiFilterVariant,
      flask: mdiFlask,
      folder: mdiFolder,
      folderCog: mdiFolderCog,
      folderStarOutline: mdiFolderStarOutline,
      home: mdiHome,
      inboxOutline: mdiInboxOutline,
      link: mdiLink,
      magnify: mdiMagnify,
      magnifyMinus: mdiMagnifyMinus,
      magnifyPlus: mdiMagnifyPlus,
      magnifyScan: mdiMagnifyScan,
      mapMarker: mdiMapMarker,
      pencil: mdiPencil,
      pin: mdiPin,
      pinOutline: mdiPinOutline,
      plus: mdiPlus,
      refresh: mdiRefresh,
      robot: mdiRobot,
      school: mdiSchool,
      shareVariant: mdiShareVariant,
      star: mdiStar,
      starOutline: mdiStarOutline,
      tagMultiple: mdiTagMultiple,
      tagOffOutline: mdiTagOffOutline,
      tagPlus: mdiTagPlus,
      textBox: mdiTextBox,
      trayArrowUp: mdiTrayArrowUp,
      trophy: mdiTrophy,
    },
    sets: {
      mdi,
    },
  },
  theme: {
    defaultTheme: 'light',
    themes: {
      light: {
        dark: false,
        colors: {
          primary: '#4a6cf7',
          secondary: '#087f5b',
          error: '#b42318',
          background: '#f5f5f5',
          surface: '#ffffff',
        },
      },
      dark: {
        dark: true,
        colors: {
          primary: '#6b8cff',
          secondary: '#5ee0b3',
          error: '#ff8a80',
          background: '#0d0d0d',
          surface: '#1c1c1e',
        },
      },
    },
  },
})
